- name: Install packages
  opkg: name={{ item }} state=present update_cache=yes
  with_items:
    - bash
    - vim
    - ruby
    - ruby-enc-extra
    - ruby-net
    - ruby-openssl
    - ruby-optparse
    - ruby-yaml
    - git
    - git-http
    - ca-certificates
    - shadowsocks-libev
